server:
  port: 8092
spring:
  application:
    name: jmssender
  rabbitmq:
    host: 192.168.5.231
    port: 5672
    username: admin
    password: admin
    template:
          retry:
            enabled: true
            initial-interval: 2
    virtual-host: /zyzh




  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
